### ISSUE TITLE
Enhancement request:  Would like Diagram.MouseDoubleClick event

### ISSUE THREAD

**Issue by TrevorDArcyEvans** [Blazor-Diagrams/Blazor.Diagrams#101]
Current workaround is to monitor Diagram.MouseClick for two clicks within a time window

**Comment by zHaytam** [comment]
Hello,
I'll try and add this in the next version. The way you do it is ultimately the "only" way to do it, so I'll just include it in the library.

**Comment by zHaytam** [comment]
This is now available in 2.1.4!
