### ISSUE TITLE
Moving ported nodes programmatically results in links rendered incorrectly

### ISSUE THREAD

**Issue by TrevorDArcyEvans** [Blazor-Diagrams/Blazor.Diagrams#102]
Steps to reproduce:
- start app
- click on 'Diagram' in sidebar
- test diagram is shown
- click on 'Update node' button

Observed:
- nodes move to right
- bottom right hand node appears detached from link
- top left hand node appears over link

Expected:
- link should be connected to ports

Notes:
- does not happen with portless nodes

[Diagram-Bug.zip](https://github.com/Blazor-Diagrams/Blazor.Diagrams/files/6475050/Diagram-Bug.zip)

**Comment by zHaytam** [comment]
Hello,
Due to the lack of time, documentation is missing on things like these. I would hope if someone can help with it :/
In order to change the position of nodes, you need to use `SetPosition`, not set `Position`. `SetPosition` takes care of updating everything. Here's how your method would become:

```
private void UpdateNode()
{
    _diagram.Nodes
        .OfType<NodeModel>()
        .ToList()
        .ForEach(nm =>
        {
            nm.SetPosition(nm.Position.X + 50, nm.Position.Y);
        });
}
```

**Comment by TrevorDArcyEvans** [comment]
Love this component :-) , so willing to do some docs.  Where should I put the info?

**Comment by zHaytam** [comment]
Maybe a new section in https://blazor-diagrams.zhaytam.com (`SharedDemo `project), tilted something like "Dynamic interactions" (I'm bad at naming, if you have better please use it). There, we can have multiple subsections on different interactions you can do programmatically, and we can start with this one.

Later, we should probably have an actual documentation website/section that's maybe more "professional".
Thank you!

**Comment by TrevorDArcyEvans** [comment]
How about a series of 'How To' pages in a 'docs' directory?

**Comment by zHaytam** [comment]
That's actually a great idea!
