### ISSUE TITLE
Link labels don't appear

### ISSUE THREAD

**Issue by serves-tea** [Blazor-Diagrams/Blazor.Diagrams#109]
Hi,
I tried to add link labels using your library's native feature but they don't appear by default (tried on Edge and Chrome).

After a little analysis of the SVG elements, I managed to make them appear by adding this little CSS workaround : 
`.link g foreignObject {
	height: 1px;
	width: 1px;
}`

But I'm not a SVG master at all, it just seemed to me that the structure/size of the elements surrounding the label prevent it from being displayed. I face the same problem in the demo where I don't see any label.

**Comment by zHaytam** [comment]
Hello,
That's very weird, it was working when the functionality was added. I believe a regression happened and/or an unwanted change was merged.

Your solution is fine, `foreignObject`s must have a x, y, width and height. 
I will fix this asap.
