### ISSUE TITLE
Moveable & scalable grid

### ISSUE THREAD

**Issue by ud-waffle** [Blazor-Diagrams/Blazor.Diagrams#113]
Hi, is there any way to implement a Moveable & scalable grid ( w/ pan and zoom respectively)?
The static approach done in the demo can be a little visually misleading
(example using litegraph.js)
https://tamats.com/projects/litegraph/editor/

**Comment by zHaytam** [comment]
Hello, I'm not a fan of it either.
I'll see if I can make it better and get back to you.

**Comment by xevoryn** [comment]
May I already have a solution to this. Have a look at [that branch](https://github.com/xevoryn/Blazor.Diagrams.Demo/tree/feature/alignment-grid) of my demo solution...

The grid is automatically enabled and can be used in `line` and `point` mode via the respective button on the top of the page.

**Comment by ud-waffle** [comment]
Thank you, got it working with your approach + some tweaks!

**Comment by zHaytam** [comment]
Hello, thanks for helping @xevoryn !
Can we leave this open please? I think I still need to add this to the library directly, and I will do it once once my sickness is gone.

Thank you!
