### ISSUE TITLE
How to place Node at center of screen 

### ISSUE THREAD

**Issue by ud-waffle** [Blazor-Diagrams/Blazor.Diagrams#115]
Hi, I'm trying to create a node dynamically and can't seem to figure out how to place the node at the exact center of the screen (independently of the pan/zoom on the diagram & the canvas size). 
Any hints?

**Comment by zHaytam** [comment]
Hello, Here's how:
```
var x = (diagram.Container.Width / 2 - diagram.Pan.X) / diagram.Zoom;
var y = (diagram.Container.Height / 2 - diagram.Pan.Y) / diagram.Zoom;
diagram.Nodes.Add(new NodeModel(new Point(x, y)));
```

If you already know the size of your nodes and want to position the node exactly at the center, then just subtract the width & height before diving on the zoom I believe.

Hope this helps
