### ISSUE TITLE
Calling ZoomToFit function on OnInitialized throws nullreference exception

### ISSUE THREAD

**Issue by Wizdore** [Blazor-Diagrams/Blazor.Diagrams#118]
ZoomToFit function throws nullreference exception when its called from the components lifecycle function.
But it works when the function is called onbutton click or any dom events. 
![image](https://user-images.githubusercontent.com/11255780/125945346-5e5e92c4-6b32-4542-a7d8-0631d9e3d8bd.png)

So I dont want the user to press a button everytime to fit the diagram on screen. Is there any workaround on this?

**Comment by zHaytam** [comment]
Hello,
Do you have a simple example to show the issue?
ZoomToFit won't really work before the canvas is rendered, because the nodes don't have sizes yet (unless you set them manually).
Still, it shouldn't throw a NullReferenceException, so that needs to be fixed.

**Comment by Wizdore** [comment]
> Hello,
> Do you have a simple example to show the issue?
> ZoomToFit won't really work before the canvas is rendered, because the nodes don't have sizes yet (unless you set them manually).
> Still, it shouldn't throw a NullReferenceException, so that needs to be fixed.

`<div class="diagramContainer" @ref="diagramContainer">
    <DiagramComp Height="_diagramDrawer.diagramHeight"
                 Width="_diagramDrawer.diagramWidth"
                 DiagramModel="_diagramDrawer.diagram"/>
</div>

@code{
    private DiagramDrawer _diagramDrawer;

    protected override void OnInitialized()
    {
        base.OnInitialized();

        _diagramDrawer = new(
            Config.visualConfig.Diagram["height"], 
            Config.visualConfig.Diagram["width"], 
            diagramConfig: Config.plantConfig
            );
        
        _diagramDrawer.diagram.ZoomToFit();

    }
}
`

Here DiagramDrawer is a class that lays out the diagram based on a json object (Config.plantConfig). 
Calling ZoomToFit OnInitialized throws the null reference exception. I found out that its happening because the bounds are not found so for now I have solved it by calling the ZoomToFit in OnAfterRenderAsync and awaiting for the bounds to be calculated. It works fine. 

`    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        
        // TODO: We can dynamicallly layout the diagrams if Elementreference of the container is passed to the
        // ToDO: Diagramdrawer. Diagramdrawer should await for the container to be rendered and only then layout nodes
        // TODO: by getting the bounds using JSruntime
        
        await base.OnAfterRenderAsync(firstRender);
        Rectangle rect = await JSRuntime.GetBoundingClientRect(diagramContainer);
        Console.WriteLine(rect);
        _diagramDrawer.diagram.ZoomToFit(20);
        
        if (firstRender)
            StateHasChanged();
    }
`

**Comment by Wizdore** [comment]
I would like to work on a fix and make a PR.

**Comment by Wizdore** [comment]
I could not reproduce the error on the sample project of this repo. I'll dig deeper whats happening.

**Comment by zHaytam** [comment]
I believe that I fixed the NullReferenceException part. It was throwing it because the nodes didn't have a `Size` yet, not because the bounds aren't here yet (that would be another exception).

Since the library needs to know the canvas container and the nodes sizes, calling `ZoomToFit` in OnInitialized will probably never work, unless you set them beforehand.
