### ISSUE TITLE
Get screen coordinates from diagram coordinates

### ISSUE THREAD

**Issue by xevoryn** [Blazor-Diagrams/Blazor.Diagrams#120]
Currently there is a way for getting the coordinates inside the diagram in relation some point on the screen by utilising `Diagram.GetRelativeMousePoint()`. 

What I can't see is a way of getting screen coordinates relative to a point inside the diagram. Is there any current way to achieve this?

If there is none than it would be useful for things like external pop-ups or tool-tips that shall be positioned alongside with a node or port.

**Comment by zHaytam** [comment]
Hi, I thought I answered this... Very sorry for the late response.
I'm assuming you already have this working? If so, please let me know and I'll tell you the formula.

I added a new method `GetScreenPoint` to serve this purpore.

**Comment by zHaytam** [comment]
This is now available in 2.1.4!
