### ISSUE TITLE
What's the best way to get notified when a link is drawn between 2 nodes?

### ISSUE THREAD

**Issue by b43r** [Blazor-Diagrams/Blazor.Diagrams#121]
Hello,

I am missing an event that notifies me when a new link is drawn between 2 nodes.
I could override the CanAttachTo method of PortModel and assume that if this method returns true, a new link is created. Still looks a bit of a hack to me... Is there a better way? Or could you add an event for that?

**Comment by zHaytam** [comment]
Hello,
- When a link is added (not attached), an `Added` event in the `Links` layer is fired, use `Diagram.Links.Added`.
- When a link is (re)attached, an `TargetPortChanged` event in the `BaseLinkModel` is fired, use `Link.TargetPortChanged`. Check if the target port is set.

Hope this helps!

**Comment by b43r** [comment]
That works, thanks!
