### ISSUE TITLE
Drag-Box multi-Link selection

### ISSUE THREAD

**Issue by xevoryn** [Blazor-Diagrams/Blazor.Diagrams#122]
As you can see in the `.gif` below we implemented a `drag-box` selection that makes it possible to not only select multiple nodes. Furthermore it is possible to select multiple links.

![Animation (10)](https://user-images.githubusercontent.com/76197715/127162724-a2d1ddd6-48da-469f-be34-fd2a1f2c41e9.gif)

The problem with our link-selection implementation is visible within the second row of nodes during the second half of the `.gif`. If the link is not straight it is possible to select it while not touching it. This is because it's evaluated as a rectangle containing the whole link.

So my question is: Is there a better way to evaluate the link as an object other than to package it as a rectangle?

**Comment by zHaytam** [comment]
Hello,

I don't know how did you make the "collision" test, so I can't comment on your specific approach.

However, what you're seeing is normal if you're testing your dragbox's rectangle against the svg element, which is also a rectangle. So the behavior you're seeing is kind of normal, as everything in HTML is rectangular, even in SVGs.

**Comment by xevoryn** [comment]
So the specific approach is simple:
- After the dragbox-rectangle has been pulled up the matching rectangle inside the Diagram will be calculated.
- The resulting rectangle is used to detect if there is an intersection to another rectangle on the canvas.

Either way you're right, everything is rectangular in HTML so it's kind of hard to estimate the exact location and shape of the link. I guess it would be possible to calculate that by implementing a custom link-type. But there is no way of getting the necessary information from the default link-type, right?

**Comment by zHaytam** [comment]
You could do it, it's just gonna take a lot of work. You will have to calculate the intersections with the calculated paths of the links, not just their bounds. The calculated paths aren't available on the models (for obvious reasons), but you can use the Routers & PathGenerators to basically regenerate that path, & then run the intersections detection.

I don't know if there is a C# library that can get you the intersections of shapes, especially SVG paths. However there is a JS one: https://github.com/thelonious/kld-intersections

**Comment by zHaytam** [comment]
I'm closing this because I think I've answered your question, there isn't much I can do without fully knowing your current code. I'm not sure if I'll be adding this type of selection to the library because, as explained, it's quite hard to get it right, but I will keep it in mind.

**Comment by snehabihani** [comment]
Hi Can you please help with this svg node dragging selection?
