### ISSUE TITLE
Move the project into .NET5.0

### ISSUE THREAD

**Issue by MaciejKubica** [Blazor-Diagrams/Blazor.Diagrams#125]
It will be awesome to update the project to use also a .net 5.0 or have a seperate solution for 5.0

**Comment by zHaytam** [comment]
Hello,
May I know why do you need the project to be in .NET 5?
You can still use the library in a .NET 5 project, and I believe it benefits from the performance improvements as well.

I'm planning to move the library to .NET 6 instead since it will be the new LTS.

**Comment by zHaytam** [comment]
Closing this because I think I anwered.
Feel free to re-open if needed!
