### ISSUE TITLE
ZoomToFit does not invoke ZoomChanged event

### ISSUE THREAD

**Issue by 314159265meow** [Blazor-Diagrams/Blazor.Diagrams#126]
Hello, 
I noticed that the ZoomToFit method doesn't invoke the ZoomChanged event. This looks like a bug to me since the method changes the Zoom value.

**Comment by zHaytam** [comment]
You're right, it only triggers the `PanChanged` event.
Thanks for letting me know, it will be fixed in the next version!

**Comment by zHaytam** [comment]
This is now available in 2.1.4!
