### ISSUE TITLE
How do I add a new node at the top-left of the viewport if zoom factor is not 1.0 ?

### ISSUE THREAD

**Issue by b43r** [Blazor-Diagrams/Blazor.Diagrams#130]
If the zoom factor is exactly 1.0 I can add a new node at the point `X = -(int)Diagram.Pan.X, Y = -(int)Diagram.Pan.Y` and it will be displayed in the top-left corner of the diagram canvas.

However if the zoom factor is not 1.0, I could not figure out a way to get the coordinates of the top-left corner.

How can I calculate these coordinates?

**Comment by zHaytam** [comment]
Hi, simply do:
```cs
var x = -diagram.Pan.X / diagram.Zoom;
var y = -diagram.Pan.Y / diagram.Zoom;
```

**Comment by b43r** [comment]
Thanks, that's really easy, don't know how I could miss that... ;-)
