### ISSUE TITLE
Duplicates resources when publishing using .NET 6 SDK

### ISSUE THREAD

**Issue by GeertvanHorrik** [Blazor-Diagrams/Blazor.Diagrams#133]
We are having duplicate resource issues with this package and we *think* it's this package only.

**Error**

```
Compressing Blazor WebAssembly publish artifacts. This may take a while...
C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ConflictResolution.targets(112,5): 
error NETSDK1152: Found multiple publish output files with the same relative path: 
C:\Users\x\.nuget\packages\z.blazor.diagrams\2.1.3\staticwebassets\default.styles.min.css.gz, obj\Release\net5.0\compress\w6oNZ7qC.gz, 
C:\Users\x\.nuget\packages\z.blazor.diagrams\2.1.3\staticwebassets\script.min.js.gz, obj\Release\net5.0\compress\b5vuy5d+.gz, 
C:\Users\x\.nuget\packages\z.blazor.diagrams\2.1.3\staticwebassets\style.min.css.gz, obj\Release\net5.0\compress\GAfSdfw+.gz.
```

**Package info**

I noticed the package already contains pre-gzipped resources:

![image](https://user-images.githubusercontent.com/1246444/130862282-99d6c3f9-6b17-4759-99e0-1e80855a325f.png)

(coming from C:\Users\x\.nuget\packages\z.blazor.diagrams\2.1.3\staticwebassets)

**Potential workarounds**

Use the `ErrorOnDuplicatePublishOutputFiles` flag:

https://github.com/dotnet/aspnetcore/blob/main/eng/Workarounds.props#L37

**More information**

For a detailed explanation, see https://github.com/dotnet/aspnetcore/issues/29524

**Comment by zHaytam** [comment]
Hi, any news about this issue?

**Comment by GeertvanHorrik** [comment]
I have added this as a workaround in the csproj:

```
  <!-- The SDK includes some conflict resolution targets that check for duplicate items in the publish targets. It's very greedy
       and ends up marking the same files in different projects as duplicates of each other. We disable this check here to work
       around this issue. -->
  <PropertyGroup>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
  </PropertyGroup>
```
