### ISSUE TITLE
node.Links should also be removed in NodeLayer.cs line 18

### ISSUE THREAD

**Issue by xhydongda** [Blazor-Diagrams/Blazor.Diagrams#137]
protected override void OnItemRemoved(NodeModel node)
        {
            Diagram.Links.Remove(node.AllLinks.ToList());
            Diagram.Links.Remove(node.Links.ToList());// <--add-->
            node.Group?.RemoveChild(node);
        }

**Comment by zHaytam** [comment]
I'm sorry I don't get it. That code is the same as now no? We're already removing the node's links.

**Comment by xhydongda** [comment]
I see, this problem was solved already.

**Comment by xhydongda** [comment]
I see, this problem was solved already.
