### ISSUE TITLE
ZoomToFit not working in 2.1.4

### ISSUE THREAD

**Issue by 314159265meow** [Blazor-Diagrams/Blazor.Diagrams#138]
Hi, thanks for fixing the `ZoomToFit` not triggering `ZoomChanged` event issue.
Unfortunately it seems like the fix broke the `ZoomToFit` function. From a quick look at the changes, I think the problem is that the lines 299 and 300
```
            var nx = Container.Left + Pan.X + minX * Zoom;
            var ny = Container.Top + Pan.Y + minY * Zoom;
```

are calculated before the `SetZoom(Math.Min(xf, yf));` call, so the pan update gets the wrong values.

**Comment by zHaytam** [comment]
Well, that's embarrassing!
I'm uploading a fix right away...
