### ISSUE TITLE
ResizeObserver bottleneck

### ISSUE THREAD

**Issue by xevoryn** [Blazor-Diagrams/Blazor.Diagrams#140]
While implementing a ResizeObserver to our own software I noticed a bottleneck in your implementation of the observer.

```javascript
ro: new ResizeObserver(entries => {
    for (const entry of entries) {
        let id = Array.from(entry.target.attributes).find(e => e.name.startsWith('_bl')).name.substring(4);
        let element = s.tracked[id];
        if (element) {
            element.ref.invokeMethodAsync('OnResize', entry.target.getBoundingClientRect());
        }
    }
}),
```

You are calling `entry.target.getBoundingClientRect()` during the invocation of the dotnet method. `getBoundingClientRect()` is expensive and one of the [layout-trashing](https://devhints.io/layout-thrashing) methods. The way better approach is to use `entry.contentRect` which is provided with the entry already.

```javascript
ro: new ResizeObserver(entries => {
    for (const entry of entries) {
        let id = Array.from(entry.target.attributes).find(e => e.name.startsWith('_bl')).name.substring(4);
        let element = s.tracked[id];
        if (element) {
            element.ref.invokeMethodAsync('OnResize', entry.contentRect);
        }
    }
}),
```

It's a little change but it will probably increase the performance by a good piece for larger diagrams.

**Comment by zHaytam** [comment]
Very interesting, thank you!
Never knew about this honestly, I'll try to apply it in the next version.

**Comment by xevoryn** [comment]
Ok, I messed up.

So there is a catch with `entry.contentRect`: after some more development time with our ResizeObserver implementation I noticed a crucial difference to `getBoundingClientRect()`. The observer only passes the targeted elements size, which results in `0` values for `x`, `y`, `left` and `top`. In other words: The observer passes the size but not the position of the target element within the client.

I am sorry that I misunderstood that and pointed that out before researching enough. I don't know if this remains to be useful for the lib because I am not far enough into the targets of your observer and if the absolute position is needed. Hopefully you can make use of the information above either way.

**Comment by zHaytam** [comment]
Right, now I remember why I was calling `getBoundingClientRect` instead of just using `contentRect`!
For the nodes, I only use the sizes. But for the canvas container, I use the positions as well, so them being 0 is a problem. This is just in case the canvas is resized and moved at the same time. The mutation observer might not pick it up.
