### ISSUE TITLE
Bug in Zoom/Pan Calculation

### ISSUE THREAD

**Issue by 314159265meow** [Blazor-Diagrams/Blazor.Diagrams#141]
Hi, 
I think I found a small bug in src/Blazor.Diagrams.Core/Behaviors/ZoomBehavior.cs. In line 41 you set the `newZoom` Variable to 
```
newZoom = Math.Clamp(newZoom, Diagram.Options.Zoom.Minimum, Diagram.Options.Zoom.Maximum);
```
But the previous value has already been used to calculate the pan change. So if you zoom to maximum/minimum, you'll notice a small viewport jump. This can be fixed if you move the lines 41-43 above the pan calculation to line 27.

**Comment by zHaytam** [comment]
Hello, sorry for the delay I thought I replied.

You are right, I can see the small viewport jump, I'll fix this in the next version! Thanks for pointing it out.
