### ISSUE TITLE
Links Rendering issue when tried to Pan large diagrams

### ISSUE THREAD

**Issue by Manjunath1205** [Blazor-Diagrams/Blazor.Diagrams#156]
When tried to load the diagram it is loading all the links properly. 
But when I tried to Pan the diagram the links are being scattered. 
When we reload the page again then the links gets loaded properly.

Please find attached diagram for reference
[](ur
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/93418648/140748030-67ed8089-181f-4452-a533-cc7a2bf9386d.png)
l)

**Comment by zHaytam** [comment]
Hello,
For this kind of problem, I really need a sample/project where I can reproduce the issue. Since I don't know what you're using and how you do things, I will probably never be able to reproduce it without your help.

Do you think it would be possible for you?

**Comment by Manjunath1205** [comment]
Can you please provide me a private channel where I can share the code?

**Comment by zHaytam** [comment]
You can send it to me by email if you'd like: haytam.zanid@gmail.com

**Comment by Manjunath1205** [comment]
I have shared the sample code and inputs.

Please also look into JSRuntime exception while zoom in , zoom out and Pan.

**Comment by zHaytam** [comment]
I can randomly reproduce the issue with the biggest dataset you gave me, it's a bit hard to pinpoint exactly what's the issue but I'm working on it.

**Comment by Manjunath1205** [comment]
Thank you for your quick response.

Awaiting for the solution.

**Comment by zHaytam** [comment]
I'm having trouble actually reproducing. There are some issues that I found in the code that I removed, but I can't reproduce the exact same issue you have...

- You shouldn't call `ZoomToFit` before everything is rendered
- You shouldn't call `SetContainer` yourself, that should be an internal method
- The orthogonal router is not very performant at the moment, so having a lot of links using it might cause a performance issue
