### ISSUE TITLE
How to use this in a razor class library.

### ISSUE THREAD

**Issue by techierathore** [Blazor-Diagrams/Blazor.Diagrams#157]
How can I use this in library in a razor class library so that I can reuse the UI in different project types. I tried to recreate the  [DB Designer ](https://github.com/Blazor-Diagrams/Blazor.DatabaseDesigner) but it didn't worked. Please help me out.  [Here is my code   ](https://github.com/techierathore/DbDesigner)

**Comment by zHaytam** [comment]
Hello, I am not sure what the issue is (you didnt mention any errors). 

All I see is that you're using a different version of the Core library in your Models project, please update that to 2.1.6 to match your other project, as that would probably cause a version mismatch.

**Comment by techierathore** [comment]
Thanks @zHaytam for quick response, I have updated the version but it didn't solved the problem. I don't get error, just diagram doesn't get loaded and button clicks  doesn't works even tough it hit's the code (I checked by putting break point in new table link click event)

**Comment by zHaytam** [comment]
Hey @techierathore, I have forked your project and managed to show everything. I created a PR in your own repository:

- In order for diagrams to show, they need to have a proper `height`.
- You forgot to include the generated scoped CSS in your project
- Imports were missing for things like `DiagramCanvas`

Hope this helps!

**Comment by techierathore** [comment]
It worked and of course helped a lot Thanks @zHaytam
