### ISSUE TITLE
Drag a node into/out of a group

### ISSUE THREAD

**Issue by chunliu** [Blazor-Diagrams/Blazor.Diagrams#158]
Is it possible to drag a node into or out of a group?

**Comment by zHaytam** [comment]
Hello! Currently, no. Moving a node expands the group. If I understand correctly, you want the group to have a fixed size? And if a node goes out or in it joins/leaves the group? It sounds like an interesting idea.

Could I know what would be an example use case? And maybe an example of a library/product that already does it so I can see it visually and how it works?

Thank you

**Comment by chunliu** [comment]
A use case could be like in a network diagram, a group can be used to represent a subnet and a node can be used to represent a VM. When I drag a VM to a subnet, I assign the VM to that subnet, and vice versa. I don't know if there is any library which can do it, but it would be great if your lib can support it.

**Comment by zHaytam** [comment]
Part of #216
