### ISSUE TITLE
null reference exception for NodePositionAdjustment  in NavigatorWidget.razor 

### ISSUE THREAD

**Issue by TimDaborn** [Blazor-Diagrams/Blazor.Diagrams#160]
Firstly Zanid, thank you for producing a great library.

As noted by b43r in issue #111, it is possible under some circumstances for NodePositionAdjustment to be null on line 3 of the NavigatorWidget.razor component.

This is because it is only initialised in the Refresh() method, but this initialisation is skipped if there are no nodes.

A simple work around is to zero initialise it as part of the declaration.

**Comment by zHaytam** [comment]
Hello,

I'm gonna be honest, the Navigator widget needs to be remade into a proper one, the current one was rushed, unfortunately. I'm trying to find the time many times right now, but I need to finish some IRL stuff first.

**Comment by zHaytam** [comment]
Part of #215
