### ISSUE TITLE
Rendering links takes more time than nodes

### ISSUE THREAD

**Issue by Manjunath1205** [Blazor-Diagrams/Blazor.Diagrams#161]
While loading the diagram to canvas, Nodes gets loaded quickly where as links takes some time to get loaded.

**Comment by zHaytam** [comment]
Hello, I did notice that as well too. Let me investigate to see why exactly it happens, then we can think of a solution.

**Comment by zHaytam** [comment]
This ended up being normal as the nodes/ports need to render first so that we get their sizes using JS, then the links can know where to position themselves.
