### ISSUE TITLE
Demo: Drag-Drop open image (firefox)

### ISSUE THREAD

**Issue by puschie286** [Blazor-Diagrams/Blazor.Diagrams#165]
When you try the drag-and-drop demo on firefox ( tested on 94.0.2, 95.0 ) the droped item is open as image.

works fine on chrome

**Comment by zHaytam** [comment]
You are right. That's weird... Let me see if I missed a `preventDefault` in some event that Firefox needs.
Thanks!

**Comment by zHaytam** [comment]
As I thought, it only works in Firefox if `ondrop="event.preventDefault()" `is used.

**Comment by wdcossey** [comment]
You need to set the `<img/>` (optionally `<span/>`) to `pointer-events:none`

i.e
```html
<div class="text-center" draggable="true">
    <img class="d-block m-auto" style="pointer-events:none;" src="_content/SharedDemo/img/DefaultNodeWidget.png">
    <span style="pointer-events:none;">Default Node</span>
</div>
```

This will stop the image accepting pointer events (i.e. `Drag`)

**Comment by wdcossey** [comment]
![drag_n_drop](https://user-images.githubusercontent.com/1089478/160502103-b6ccb329-25f6-4346-a181-112531fca72a.gif)
