### ISSUE TITLE
Exception when diagram is being toggled in a render fragment.

### ISSUE THREAD

**Issue by PhoenixChua13** [Blazor-Diagrams/Blazor.Diagrams#168]
Hi, so I'm using v2.1.6 of the library in Blazor Server and have a diagram in a collapsable component (where a button is used to toggle the render fragment of the collapsable component on and off). When deployed to Azure App Service, toggling the diagram on and off is triggering an ObjectDisposed exception in the ObserveResizes function (does not happen locally); I think the javascript is getting out of sync with Blazor.

Would it be possible to add some code catch the ObjectDisposed exception? 

<img width="758" alt="BlazorDiagramException" src="https://user-images.githubusercontent.com/83267633/146845422-2964b1bb-3ae9-49d2-a9f5-7a07aad2fe83.PNG">

Thanks for your work on the library by the way!

**Comment by zHaytam** [comment]
A possible fix has been added to 3.0.0
