### ISSUE TITLE
Placing an InputText form in a custom link label.

### ISSUE THREAD

**Issue by EdwardCalvert** [Blazor-Diagrams/Blazor.Diagrams#170]
Hi!

I'd like to create a custom link label, with an Input Text component, so the user can give the length of the edge (but I'm not looking to change the length as I am aiming to create a interactive Dijkstra's path ). The kind of thing I am looking for is:

![image](https://user-images.githubusercontent.com/72658447/147768704-d7033c65-9e9e-4189-9868-4cfc8857f12a.png)

I have used the guide here:
https://github.com/Blazor-Diagrams/Blazor.Diagrams/tree/master/docs/CustomNodesLinks . And attempted to add the form in the DiagramLinkLabelWidget.razor component. The link label is drawn as an svg, which means the user can't edit the form.

How would I go about implementing such a feature?

**Comment by zHaytam** [comment]
Hello!

What you're trying to do requires proper SVG, which I believe is only available in .NET 6. Which version are you using?

**Comment by EdwardCalvert** [comment]
Thanks for the tip- I'm now targeting .NET 6 and was successfully able to create a SVG with a form inside.

How do I allow the user to interact with the form, as it currently is not a selectable item? It looks like it is attempting to move the background.
![image](https://user-images.githubusercontent.com/72658447/147780891-6ed96a0f-b392-47c3-9ac3-46392728f939.png)

**Comment by zHaytam** [comment]
Could you please give me a sample code I can quickly test to see the issue? Maybe your custom link's HTML?

**Comment by EdwardCalvert** [comment]
The code for the Label is this:
```
<foreignObject class="graphml-link" x="@X.ToInvariantString()" y="@Y.ToInvariantString()">
        <div style="font-size:16px;" class="link-label" >
        <EditForm Model="Label">
            <InputNumber class="form-group" @bind-Value="Label.EdgeDistance" style="width:40px; pointer-events: all;"  ></InputNumber>
        </EditForm> 
        </div>
    </foreignObject>
```
The code for the whole component is here:
https://github.com/EdwardCalvert/FurtherMathsAlgorithms/blob/master/FurtherMathsAlgorithms/Widgets/DiagramLinkLabelWidget.razor

After I applied the style `pointer-events: all;`, I was then able to interact with the form. The only peculiarity is that I am only able to use the decrement stepper. Do you know why that may be?

**Comment by zHaytam** [comment]
Hi, sorry for the late reply...
I can't access the component code, the repository is probably private.
What UI library are you using?

**Comment by EdwardCalvert** [comment]
No worries, I've updated the repo to public. 

I'm not aware I'm using a UI library at all! Just the Z.Blazor.Diagrams NuGet package.

**Comment by zHaytam** [comment]
This is very weird... Just looked at it for 30 minutes, I can't figure out why it happens only inside the diagrams...
I'll try more things later today or tomorrow.

**Comment by EdwardCalvert** [comment]
Thank you so much for your efforts. 

As there is no _"easy"_ fix, I ended up removing the setter through CSS. 
```/* Chrome, Safari, Edge, Opera */
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

/* Firefox */
input[type=number] {
  -moz-appearance: textfield;
}
```
Thanks again for your help!
