### ISSUE TITLE
.NET 6 Unknown error occurred while trying to verify integrity.

### ISSUE THREAD

**Issue by jvetter713** [Blazor-Diagrams/Blazor.Diagrams#173]
Failed to find a valid digest in the 'integrity' attribute for resource 'https://localhost:7285/_framework/Blazor.Diagrams.dll' with computed SHA-256 integrity '47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='. The resource has been blocked.

Blazor Web Assembly
.NET 6

Any ideas?

**Comment by zHaytam** [comment]
Hello,

Does it only happen with Blazor.Diagram.dll? Usually the integrity problems aren't caused by the libraries themselves.

**Comment by jvetter713** [comment]
I'll take a screen shot... There was one more - an svg dll. The CSS and Js includes I added to index.html also were blocked.

Jason

------- Original Message -------

**Comment by jvetter713** [comment]
![Z Blazor Diagram](https://user-images.githubusercontent.com/2367086/151438239-6c7e4026-e6c3-4fbb-b4a8-b34d50658412.jpg)

**Comment by zHaytam** [comment]
It looks like a lot of things fail the integrity check, please verify how you deploy your solution as this isn't related to this library.
