### ISSUE TITLE
Nested groups?

### ISSUE THREAD

**Issue by JBBianchi** [Blazor-Diagrams/Blazor.Diagrams#177]
Hello,

Is there any plan on the roadmap to lift the [current limitations](https://github.com/Blazor-Diagrams/Blazor.Diagrams/issues/38#issuecomment-735377015) for the groups, and especially nesting?

Thanks a lot for your work.

**Comment by JBBianchi** [comment]
nvm, it seems to be, I should have checked the sources first: https://github.com/Blazor-Diagrams/Blazor.Diagrams/blob/master/src/Blazor.Diagrams/Components/Groups/GroupNodes.razor

**Comment by zHaytam** [comment]
Hi, with the way it works right now (nested in the DOM too), you might see some unwanted behavior.
Maybe it would be better to implement them differently, we'll see.

**Comment by JBBianchi** [comment]
I didn't dig too far yet but, conceptually, it seems to make sense to have them nested in the DOM. Let me know if I can be of any help.
