### ISSUE TITLE
Request: Comparison support for Point

### ISSUE THREAD

**Issue by jchown** [Blazor-Diagrams/Blazor.Diagrams#192]
I went to use `Point` for my own purposes (in my case, for monitoring a "dirty" state).

I wasn't able to because `Point` really needs `Equals()` and `GetHashCode()` implementations for ease of use.

(I'll use my own for now,)

**Comment by zHaytam** [comment]
In the new version, which uses .NET 6, `Point` will be a record so that will be fixed.
