### ISSUE TITLE
Read only mode

### ISSUE THREAD

**Issue by DarkEyeDragon** [Blazor-Diagrams/Blazor.Diagrams#193]
Is there a way to make diagrams read only (so you cant drag nodes around and such)?

Couldn't find anything about it on the docs.

**Comment by 314159265meow** [comment]
Hi, there is a `Locked` property for that. 

https://blazor-diagrams.zhaytam.com/demos/locked  
https://github.com/Blazor-Diagrams/Blazor.Diagrams/blob/master/samples/SharedDemo/Demos/Locked.razor.cs

**Comment by zHaytam** [comment]
I'll close this since there was no response.
