### ISSUE TITLE
HEALTH ISSUES - lack of activity

### ISSUE THREAD

**Issue by zHaytam** [Blazor-Diagrams/Blazor.Diagrams#197]
Hello,
I'm creating this issue to quickly explain the lack of activity in this repository.
I've been having health issues these last months and I'm on an "adventure" to fix them (first, figure them out).
Once I get better (hopefully), I'll keep working on this project because I love it.

**Comment by faramos** [comment]
Hello,
I hope you get better soon.
Best wishes!
