### ISSUE TITLE
PortAlignment.Left and PortAlignment.Right positioned wrong in custom nodes

### ISSUE THREAD

**Issue by RonSijm** [Blazor-Diagrams/Blazor.Diagrams#198]
Reproduce: 
- Go to the shared demo project
- SharedDemo.Demos.CustomNodeComponent
- private BotAnswerNode NewNode(double x, double y)
- Add `node.AddPort(PortAlignment.Left);` and `node.AddPort(PortAlignment.Right)`
- Run the project

![image](https://user-images.githubusercontent.com/337928/169982606-e307c92c-7345-412c-a84b-04b9826baa17.png)

I also don't see any way to manually place the ports. Not sure if I'm missing something.

Have the same issue in my own project, where they appear on a kinda random spot:
![image](https://user-images.githubusercontent.com/337928/169983347-22528cc3-12b3-40cd-9654-708f5a6eefc7.png)

**Comment by zHaytam** [comment]
Hello,

You can see here (https://github.com/Blazor-Diagrams/Blazor.Diagrams/blob/master/samples/SharedDemo/wwwroot/css/styles.css#L1553) that there is CSS only for the top and bottom ports.

The way you position your own ports is through CSS as well. So add some to your project and you should be able to do everything you want. Does that help?
