### ISSUE TITLE
can we support drawing links between nodes by users themselves 

### ISSUE THREAD

**Issue by jessetalk** [Blazor-Diagrams/Blazor.Diagrams#206]
to support draw a link between two nodes (do it by user themself)

1. change the node's background when mouse move over it, and change the mouse‘s shape to cross
2. press down the mouse begin to draw the virtual/fake line
3. while draing, drawing the virtual/fake line from the start point to where the mouse go
4. until the mouse move over to another node, and release the mouse, create a link between the source node and the target node.

**Comment by jessetalk** [comment]
after digging into the source code of demo, i think my question was to support drawing portless links by user themselves, is there any one know how to do this?

**Comment by zHaytam** [comment]
Hello,
Unfortunately, it's not possible right now :/ But I should start working on it very soon!

**Comment by jessetalk** [comment]
> Hello, Unfortunately, it's not possible right now :/ But I should start working on it very soon!

that's so cool . looking forward to it~

**Comment by zHaytam** [comment]
Part of #213.
