### ISSUE TITLE
Review/add events

### ISSUE THREAD

**Issue by zHaytam** [Blazor-Diagrams/Blazor.Diagrams#214]
- Node position changed (at the end of a drag).
- Clearly differentiate between link addition (start drag) vs link attached (should be a new event)
- Add more useful events

**Comment by ashortland-eqix** [comment]
Any tips on how this works "Clearly differentiate between link addition (start drag) vs link attached (should be a new event)"?  I'm specifically looking for how to handle link attached event

**Comment by zHaytam** [comment]
Hello,
To know when a link started to get dragged, check `Diagram.Links.Added`, if you want to check if the link got attached to something else, then use the previous event and then register to the link's `TargetChanged` event
