### ISSUE TITLE
Option to send to background

### ISSUE THREAD

**Issue by Aurimas-TheDev** [Blazor-Diagrams/Blazor.Diagrams#222]
I am looking for a way to send particular nodes to background, so link would be on top of the node. For example there are 3 nodes going one by one to the left: a, b and c. Then a and c nodes linked, thus link "line" goes over node b

**Comment by zHaytam** [comment]
This is something added to 3.0.0 (work in progress).

In the meantime, try to set the z-index of the svg layer to 2 and the html layer to 1, you might get some side effects and we can talk about them here next.

**Comment by zHaytam** [comment]
Now that i re-read the question, ordering specific elements is not currently supported sorry. I will try to add it in 3.0.0 and it will only be available for svg nodes, since we can't enforce an order between html nodes and svg links.

**Comment by Aurimas-TheDev** [comment]
Thanks for replies, perhaps I can workaround with svg nodes,can you give me an example how to create one?

**Comment by zHaytam** [comment]
3.0.0 beta 4 now includes a new Ordering system, with two new methods as well: `SendToFront` and `SendToBack`.
Please check it out !
