### ISSUE TITLE
Snap to Grid loses track of grid background when Zooming or Panning

### ISSUE THREAD

**Issue by 240026763** [Blazor-Diagrams/Blazor.Diagrams#229]
In your Snap to Grid example and the Larger application example, the snap to grid is nice but the grid is static and doesn't scale when zoomed and doesn't move when panning so that grid background just becomes an annoyance.

**Comment by zHaytam** [comment]
A new `GridWidget` has been added to 3.0.0, which is dynamic.
See #113
