### ISSUE TITLE
Enhancement request: Auto-select all links on node click

### ISSUE THREAD

**Issue by rslavey** [Blazor-Diagrams/Blazor.Diagrams#258]
I'm using this tool to generate a graph based on data from a database. I have it laid out and it looks good. What I'd like to be able to do is click on a node and all of the connected links are highlighted so the person looking at the graph can easily see parent and child nodes for this node (we use top connections for parents, bottom connections for children, like a flowchart).

I thought it might be as simple as setting the link to "Selected" in code, but it is read-only.

![image](https://user-images.githubusercontent.com/21177142/198153287-674dc70d-817a-425c-861c-1363e7c616ea.png)

Desired result:

![image](https://user-images.githubusercontent.com/21177142/198153601-6d4e9ca1-79b6-407a-82c6-5aba2403e62b.png)

**Comment by zHaytam** [comment]
Hi, please use `Digram.Select` instead. Something like this should work:
```
Diagram.UnselectAll();

foreach (var link in ...)
{
    Diagram.SelectModel(link, unselectOthers: false);
}
```
