### ISSUE TITLE
. net6.0 supports desktop program packaging 

### ISSUE THREAD

**Issue by tsxylhs** [Blazor-Diagrams/Blazor.Diagrams#259]
. net6.0 supports desktop program packaging. Whether the component supports it or not, and whether there are examples for reference. thank you.

**Comment by zHaytam** [comment]
I'm sorry I don't really get the question.
Do you want to use this library in a desktop app? If yes, check out Blazor Hybrid.

**Comment by tsxylhs** [comment]
Yes, I tried to load the library with the Blazor Hybrid implementation, but there was still a problem with desktop rendering. I'll try again

**Comment by 240026763** [comment]
Not an issue. I have this running in a WPF application fine using the mentioned BlazorWebView Control.
