### ISSUE TITLE
Nullreference exception when adding link model target/source ports

### ISSUE THREAD

**Issue by AlmightyLks** [Blazor-Diagrams/Blazor.Diagrams#263]
For some reason the following code throws a NRE
Am I doing something wrong?
```cs
            Diagram.Nodes.Add(current);

            if (parent is not null)
            {
                var link = new LinkModel(parent, current)
                {
                    TargetMarker = LinkMarker.Arrow
                };
                link.SetSourcePort(parent.GetPort(PortAlignment.Bottom));
                link.SetTargetPort(current.GetPort(PortAlignment.Top));
                Diagram.Links.Add(link);
            }
```

![image](https://user-images.githubusercontent.com/54688434/200807325-b6c34b2e-c899-45b5-acd7-3f8a0e66bc82.png)

Stacktrace:
```
   at Blazor.Diagrams.Core.Layers.LinkLayer.OnItemAdded(BaseLinkModel link)
   at Blazor.Diagrams.Core.BaseLayer`1.Add(T item)
   at ForkHierarchy.Pages.Index.<RenderNodeAsync>d__24.MoveNext()
```

Checking whether I am adding a null value to SetSource/TargetPort, shows me that they do have values:
![image](https://user-images.githubusercontent.com/54688434/200808003-2bb9e30a-3680-4e29-8fbe-df1aad39a741.png)

**Comment by AlmightyLks** [comment]
Oh and the reason why I suspect the source / target port setters is, that it doesnt occur when not setting them:
![image](https://user-images.githubusercontent.com/54688434/200808602-3d590154-6522-401a-a392-a963abc396b8.png)

**Comment by AlmightyLks** [comment]
Digging into this:
![image](https://user-images.githubusercontent.com/54688434/201437620-9940150f-54d2-4250-a575-8ff1f3478110.png)

**Comment by zHaytam** [comment]
Hello, what version are you using?

**Comment by AlmightyLks** [comment]
Latest stable release, 2.1.6

Debugging the current master branch source to investigate

**Comment by AlmightyLks** [comment]
![image](https://user-images.githubusercontent.com/54688434/201438466-a4089167-584f-44a6-a6fa-4d978f3b0dde.png)
When `Node#GetPort()`, shouldn't the returning Port's parent be the Node I used it on? ^^

**Comment by zHaytam** [comment]
Is there a possibility `SourceNode` is null? Even though it seems impossible, since its being set in https://github.com/Blazor-Diagrams/Blazor.Diagrams/blob/master/src/Blazor.Diagrams.Core/Models/Base/BaseLinkModel.cs#L70

**Comment by zHaytam** [comment]
> ![image](https://user-images.githubusercontent.com/54688434/201438466-a4089167-584f-44a6-a6fa-4d978f3b0dde.png) When `Node#GetPort()`, shouldn't the returning Port's parent be the Node I used it on? ^^

Interesting. Can you show me how are you creating these nodes and ports?

**Comment by AlmightyLks** [comment]
![image](https://user-images.githubusercontent.com/54688434/201439008-92849a31-c0b7-449d-ab33-226e07968863.png)

I think this is the only place where I create both, the node models and then ports

**Comment by zHaytam** [comment]
The type of `SourcePort` is `NodePort`?
This is very wierd... The only way Parent could be null is if you pass null to it. Cna you show me the NodePort class?

**Comment by AlmightyLks** [comment]
![image](https://user-images.githubusercontent.com/54688434/201441460-3af89723-f192-4072-9651-e4a174a866ce.png)
Oh, funny thing. I had this in my portmodel


Is the parent the node's parent or is the parent the node itself?

**Comment by zHaytam** [comment]
A port's parent is the node itself. A node doesn't have a parent (at least in the library, so that might be your own property?)

**Comment by AlmightyLks** [comment]
Would make sense, yeah 😄

**Comment by AlmightyLks** [comment]
One more question related to this feature
![image](https://user-images.githubusercontent.com/54688434/201443940-f7e34056-1598-4795-a388-2f205793967b.png)
It isn't showing any links at all now 😄 

Am I using it right?

**Comment by zHaytam** [comment]
I'll need more information. Firstly, how are you rendering your ports?

**Comment by AlmightyLks** [comment]
Oh! I didn't know you had to add a PortRenderer to the custom node razor file! 😄 
My bad

With this all my questions in this regards were answered. Thanks
