### ISSUE TITLE
Link without svg path

### ISSUE THREAD

**Issue by elgransan** [Blazor-Diagrams/Blazor.Diagrams#267]
Hi, I'm creating a link between 2 nodes and seems to be created correctly but as I can see the svg path it isn't generated

![image](https://user-images.githubusercontent.com/9949584/202509998-be1758c9-3cc5-4b5c-b666-21fcf3b34adb.png)

Any idea what I'm doing wrong?

 this is my code (It's based on [DatabaseDesigner](https://github.com/Blazor-Diagrams/Blazor.DatabaseDesigner) project)

        foreach (var clink in columnsLink)
        {
            var parent = ...
            var child = ...

            var nodeParent = (Table)Diagram.Nodes.First(s => ((Table)s).Name == parent.Label);
            var nodeChild = (Table)Diagram.Nodes.First(s => ((Table)s).Name == child.Label);
            var childColumn = nodeChild.Columns.First(s => s.Name == clink.Label);
            var link = new LinkModel(nodeChild.GetPort(childColumn), nodeParent.GetPort(PortAlignment.Left));
            Diagram.Links.Add(link);
        }

**Comment by zHaytam** [comment]
Hello, please show me your code for the node widget.
A link wont output anything if it can't get the positions it needs (e.g. ports not rendering, sizes not fetched)

**Comment by elgransan** [comment]
Ok, that hint was enough, I defined PortAligment.Right to "key" column, but I'm rendering it at the left.
Thanks!!
