### ISSUE TITLE
I can't render orthogonal

### ISSUE THREAD

**Issue by elgransan** [Blazor-Diagrams/Blazor.Diagrams#268]
Hi, I have another problem that I can't figure out. I want straight router and orthogonal path generator but

If I set it globally
![image](https://user-images.githubusercontent.com/9949584/202559091-432b3d17-ecdb-46c8-97e3-e60b2195c214.png)

I get 
![image](https://user-images.githubusercontent.com/9949584/202559558-54251f7a-04e2-46a2-8906-ac9f8c19558b.png)

And if I do it link by link
![image](https://user-images.githubusercontent.com/9949584/202559645-049b35ff-945d-4c01-bfc4-74649f3e1c72.png)

I get
![image](https://user-images.githubusercontent.com/9949584/202559316-6b7cbaa0-224d-4b16-89bc-70c2eb3235c5.png)

Any idea?

**Comment by elgransan** [comment]
Ok, I could understand that the problem is the Source Parent Size which is null, but I don't know why

![image](https://user-images.githubusercontent.com/9949584/203821785-e028d774-951e-499a-8a6c-268f0fe3e246.png)

**Comment by zHaytam** [comment]
Hello,
In your node widget, are you using `PortRenderer` to actually render the ports? If their size is null that means they probably didn't render or they're not "visible" in the DOM, which means we can't really know their size and position.

**Comment by elgransan** [comment]
Yes, in fact, the links are displayed using "normal" router

![image](https://user-images.githubusercontent.com/9949584/203828740-ab84fdf4-1154-43bd-a299-842ca37037c1.png)

I also forced a Size, and now I think is another problem

**Comment by zHaytam** [comment]
Would it be possible for you to host the project in GitHub so that I take a look at it? If it dosen't have anything confidential

**Comment by elgransan** [comment]
I will try to extract it from the whole project, thank! BTW the project is awesome

**Comment by elgransan** [comment]
Ok I published my code on https://github.com/elgransan/Blazor.DatabaseDesigner, It will be great if you can take it a look on it, when you can.

**Comment by zHaytam** [comment]
I have a feeling it's because the ports are not on the borders. I'm doing more tests to make sure

**Comment by elgransan** [comment]
Yes it was!!

![image](https://user-images.githubusercontent.com/9949584/203995664-6650ce47-9105-4cef-a933-82894f0c26ac.png)

**Comment by zHaytam** [comment]
Hum, that feels like a bad limitation. I'll see what I can do.

**Comment by sajjadarashhh** [comment]
i have same issue with this!
@zHaytam

**Comment by sajjadarashhh** [comment]
![image](https://github.com/Blazor-Diagrams/Blazor.Diagrams/assets/72276897/dcf6041e-96c9-44b0-aad5-ed9eb9ef90ff)
as you see here all links create by one method you can show below:
`                Diagram.Links.Add(new LinkModel(this.GetPort(PortAlignment.Right), item.GetPort(PortAlignment.Left))
                {
                    Router = new OrthogonalRouter(),
                    PathGenerator = new StraightPathGenerator(5)
                });`
after size Changed event i re-set positions and Create links children given Orthogonal Routing but parents is not giving that works fine!
i dont know why ! :\
