### ISSUE TITLE
Diagram Container vs Pan(-el?)

### ISSUE THREAD

**Issue by AlmightyLks** [Blazor-Diagrams/Blazor.Diagrams#269]
What's what here exactly?
I am getting a little confused about their meaning, and I can't seem to find any docs explaining them

**Comment by AlmightyLks** [comment]
Adding to this:
I just noticed, the Pan is a simple Point; Which confuses me even more

**Comment by zHaytam** [comment]
Hello,

- Container: This is the bounding rectangle of the diagram canvas. It reprensents the size of the canvas and the offset (top/left). It is used to calculate things like the point in a diagram from the clientX etc.
- Pan: This is the offset of the diagram itself. If you grab and move the canvas to the right, the pan will be (SomeNumber, 0), which tells you that everything needs to be moved by that much.

Hope this helps.

**Comment by zHaytam** [comment]
![image](https://user-images.githubusercontent.com/34218324/202847222-c9299b45-dcea-46d0-8591-d42ae3a619aa.png)

Me trying to explain with a drawing 😂

**Comment by AlmightyLks** [comment]
I am not certain how I'd manage to move the Diagram to the position of a Node 😄 
Is there a way of achieving that?

**Comment by zHaytam** [comment]
If your node is the only one selected, you can use `Diagram.ZoomToFit`.
Otherwsise, there is a PR still in progress: https://github.com/Blazor-Diagrams/Blazor.Diagrams/pull/178

**Comment by AlmightyLks** [comment]
Is there a way to make it select a node programmatically? 😆

**Comment by zHaytam** [comment]
Yes! `Diagram.SelectModel(yourNode, unselectOthers: true)`

**Comment by AlmightyLks** [comment]
That does move the Pan to the node's top left position; 
The margin parameter of `ZoomToFit` allows for a margin. However that margin affects the zoom as well, no way to position it to center? 😄

**Comment by zHaytam** [comment]
If you want it in the center, that will require a bit more calculations.
The container is not really used like that. Container is only used (mostly) internally to understand how to shif things.

If you want things to be in the middle, you will have to adjust the pan yourself by:

1. Set the node position to 0,0 (or call ZoomToFit with margin 0)
2. Setting Pan.X to HalfContainerWidth - HalfNodeWidth
3. Setting Pan.Y to HalfContainerHeight - HalfNodeHeight

I can provide an example code once I get on my computer.

**Comment by AlmightyLks** [comment]
```cs
            Diagram.SelectModel(_rootNode, unselectOthers: true);
            Diagram.ZoomToFit();
            Diagram.SetPan(
                (Diagram.Container.Width / 2) - (_rootNode.Size.Width / 2),
                (Diagram.Container.Height / 2) - (_rootNode.Size.Height / 2)
                );
```

Seems fitting to what you described

![image](https://user-images.githubusercontent.com/54688434/202873256-b2a6b235-6db5-441d-894a-97772d5a35e9.png)

doesn't position it as good however 😄

**Comment by AlmightyLks** [comment]
On the side, to not undermine your efforts: I appreciate your patience and help!

**Comment by AlmightyLks** [comment]
Oh! I found a mistake on my side!

**Comment by zHaytam** [comment]
There is a mistake on my side too, my idea would only work if your node is at 0,0. I can provide a working example tomorrow if you still don't have a solution

**Comment by AlmightyLks** [comment]
I am still open to hear about the centering code snippet, as I did not manage to do it myself, admittedly 😅

**Comment by zHaytam** [comment]
Hello!

Please try the following extension method:
```
public static void CenterOnNode(this Diagram diagram, NodeModel node, double margin = 0)
{
    diagram.SelectModel(node, unselectOthers: true);
    diagram.ZoomToFit(margin);

    var width = node.Size.Width * diagram.Zoom;
    var scaledMargin = margin * diagram.Zoom;
    var deltaX = (diagram.Container.Width / 2) - (width / 2) - scaledMargin;
    diagram.UpdatePan(deltaX, 0);
}
```

**Comment by AlmightyLks** [comment]
Yes! That does the job! Thanks a lot! 😄
