### ISSUE TITLE
SelectionBoxWidget

### ISSUE THREAD

**Issue by dstickel** [Blazor-Diagrams/Blazor.Diagrams#273]
How is the SelectionBoxWidget used? Is there an example of this? I have tried implementing it without any luck.

**Comment by zHaytam** [comment]
Hello! Did you figure it out?
I'm currently reworking the website and docs so everything will be availble.

**Comment by dstickel** [comment]
Hello,
         Yes I did. I figured it out about five minutes after reporting that issue request. I am interested in adding a similar widget that could be used for adding nodes. In a situation like the drag and drop demo. Making the list of nodes, divs in the demo, as models and drawing the node in the diagram. Does this sound possible?

Thanks for the follow up.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by dstickel** [comment]
How can you dynamically resize the node model? With a button or other means? I have tried a few things and see the square in the Navigator Widget increase in size but the node in the diagram never does.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by zHaytam** [comment]
Did you call `Refresh` on the node? So that its widget updates
