### ISSUE TITLE
I hope to get your help

### ISSUE THREAD

**Issue by tsxylhs** [Blazor-Diagrams/Blazor.Diagrams#274]
I created a desktop application with blazer, maui and antAntDesign. The package test on MacOS can achieve the drag effect, but the drag effect is disabled when packaging on the window system. Can you help me find out what caused it.
Code address:  [code](https://github.com/tsxylhs/blazorDemo)  

Thanks

**Comment by zHaytam** [comment]
I will close this since there was no reply to your questions. 
Feel free to re-open if you still have the issue!
