### ISSUE TITLE
Script.js Unobserver Throw

### ISSUE THREAD

**Issue by adrien426** [Blazor-Diagrams/Blazor.Diagrams#281]
![image](https://user-images.githubusercontent.com/9755757/205945479-667aa327-2bf2-48c5-a5af-69cf29725c25.png)
The script does not test if the element is not nul :  
![image](https://user-images.githubusercontent.com/9755757/205945651-738cabab-df3d-4b3c-9826-50ea6c32aed8.png)
To fix this issue,
I added a test before doing these actions:
```
  if (typeof (element) != 'undefined' && element != null) {
            s.ro.unobserve(element);
            delete s.tracked[id];
            delete s.canvases[id];
    }
```
In project: **Blazor.Diagrams** 
File: **wwwroot/script.js** 
Line: **41**

**Comment by zHaytam** [comment]
Hello, is this using version 2.1.6?
