### ISSUE TITLE
Exception when scrolling page

### ISSUE THREAD

**Issue by glinkot** [Blazor-Diagrams/Blazor.Diagrams#286]
Not sure if it relates to the other issue I raised, but there's an exception when scrolling.  It's pretty easy to replicate, create a diagram (you could use the project I provided earlier), use the mousewheel to scroll down/up randomly near the bottom of the page, letting the zoom effect occur on the diagram.  I'm not sure what triggers the diagram to 'unobserve' resizing - perhaps when it become no longer visible?  

![Scrolling Exception](https://user-images.githubusercontent.com/13640691/206385373-44f41e1b-514e-4ab2-93c5-e33ae9d058b3.gif)

Sorry for logging 3 things so quickly, I'm just exploring your awesome work, and at the moment lack the understanding to diagnose what's causing them.

**Comment by zHaytam** [comment]
Yep this is a known issue. It has been fixed in 3.0.0

**Comment by glinkot** [comment]
Great, thanks!
