### ISSUE TITLE
Labels do not display

### ISSUE THREAD

**Issue by dandeto** [Blazor-Diagrams/Blazor.Diagrams#288]
Labels do not display when I use the sample code found here: https://github.com/Blazor-Diagrams/Blazor.Diagrams/blob/master/samples/SharedDemo/Demos/Links/LabelsDemo.razor.cs
My label does show up in the svg code, it's just not rendering. Also, this issue is present on the demo online here: https://blazor-diagrams.zhaytam.com/links/labels

Related: #109

![image](https://user-images.githubusercontent.com/16432103/206820042-e361077a-5e63-43f0-874c-ac724dc4ae88.png)
![image](https://user-images.githubusercontent.com/16432103/206820073-f1ce72e4-7f4b-459f-9a6d-8b9de6118cae.png)
```
<foreignObject x="226.00193303765604" y="162.89994599331078">
<div class="link-label">content</div>
</foreignObject>
```

I haven't tried the pre-release to see if it's fixed there...

**Comment by zHaytam** [comment]
Hello,

I can see the labels in the demo website... What browser are you using?
Can you check if the foreignObejct contains `overflow: visible;`

**Comment by dandeto** [comment]
I use firefox, but I can see them in chrome. Yes, foreignObject contains `overflow: visible`

**Comment by zHaytam** [comment]
I just downloaded Firefox and you are right, they don't show.
I am investigating.

**Comment by zHaytam** [comment]
This fixes it for me:

```
.link foreignObject {
  width: 100%;
  height: 100%;
}
```

I will be adding it in 3.0.0, please confirm it works for you as well

**Comment by prof3000** [comment]
Good day please help small example how to make color circle and box make in diagram with text
