### ISSUE TITLE
Source ports and target ports

### ISSUE THREAD

**Issue by elgransan** [Blazor-Diagrams/Blazor.Diagrams#295]
Hi, it is possible to set a port as only source and other as only target?

**Comment by zHaytam** [comment]
Hello,

You can create a custom class and inherit from `PortModel`, then override `CanAttachTo` to include whatever logic you need. 
In your case, a simple `bool` property `IsSource` for example can do the job, then the new method could look something like:

```cs
public override bool CanAttachTo(PortModel port)
            => base.CanAttachTo(port) && IsSource != port.IsSource;
```

**Comment by elgransan** [comment]
Hi thanks it's working perfect using aligments in this way

> 
    public override bool CanAttachTo(PortModel port)
            => Alignment == PortAlignment.Bottom && port.Alignment == PortAlignment.Top;

But I had to remove base method call because I couldn't connect itself, It's the correct way to allow connecting itself?

Thanks!

**Comment by zHaytam** [comment]
Yes, check out https://github.com/Blazor-Diagrams/Blazor.Diagrams/blob/master/src/Blazor.Diagrams.Core/Models/PortModel.cs#L51

**Comment by elgransan** [comment]
Perfect thanks a lot!
