### ISSUE TITLE
[3.0 pre-release] Links dont connect to Ports

### ISSUE THREAD

**Issue by AlmightyLks** [Blazor-Diagrams/Blazor.Diagrams#298]
![image](https://user-images.githubusercontent.com/54688434/215591875-5f831d06-e4e2-42aa-853e-f8d182b57d31.png)

Migrating from v2 to v3, the links don't connect to the ports anymore  
The ports however are rendered within the model properly, so that part should be fine

**Comment by zHaytam** [comment]
Hey,

Can you tell me what you changed from v2 to v3?

**Comment by AlmightyLks** [comment]
![image](https://user-images.githubusercontent.com/54688434/215758508-167c08ca-42cb-475b-8a3c-db16455d083b.png)

![image](https://user-images.githubusercontent.com/54688434/215758552-a2e835b2-b241-408d-8467-be8b806402f0.png)

![image](https://user-images.githubusercontent.com/54688434/215758633-82b9563b-1458-453d-91bf-ba633f6be14d.png)

**Comment by zHaytam** [comment]
Using v2, the port was also in the same position? Because it looks a bit to the left side?

**Comment by zHaytam** [comment]
Im guessing when you move the nodes the links are still out of place?

**Comment by AlmightyLks** [comment]
Yep

**Comment by zHaytam** [comment]
Can you upload me the project as is? I don't want to do these changes to my other clone since I'm cehcking the performance problem in that one

**Comment by AlmightyLks** [comment]
Latest v3 state is up on [the repo](https://github.com/AlmightyLks/ForkHierarchy/)
Snatch the zip clone 😄

**Comment by zHaytam** [comment]
Hey, found the issue!

Since your ports don't really have a shape (0 height), the `SinglePortAnchor` returns a wrong position because `UseShapeAndAlignment` is true by default.

Change your ports initiation to:
```cs
if (current.Parent.GetPort(PortAlignment.Bottom) is { } sourcePort)
    link.SetSource(new SinglePortAnchor(sourcePort) { UseShapeAndAlignment = false });

if (current.GetPort(PortAlignment.Top) is { } targetPort)
    link.SetTarget(new SinglePortAnchor(targetPort) { UseShapeAndAlignment = false });
```

![image](https://user-images.githubusercontent.com/34218324/216817359-b3055df2-eb98-441e-93e8-b99531bdd76c.png)

**Comment by AlmightyLks** [comment]
Oh wow! 😄 
Yeah, I would've never found that

Thanks!
