### ISSUE TITLE
Ports of custom node does not appear on diagram

### ISSUE THREAD

**Issue by Berkayreb** [Blazor-Diagrams/Blazor.Diagrams#301]
Hello my friend,

Firstly thank you so much for this nice library. 

I try to add custom node with ports. But ports doesnt seen on page like image.
![image](https://user-images.githubusercontent.com/45543505/220666795-271c8936-bb32-42f1-80b0-b64b8023065c.png)

My codes :

![image](https://user-images.githubusercontent.com/45543505/220667453-6560ab76-8c27-4c2c-bc6a-c1a5ab9498b1.png)

![image](https://user-images.githubusercontent.com/45543505/220667492-e54be602-a5b4-4be3-b7de-5b35072d1389.png)

How can i fix this? Can you help? 

Thank you in advance for your reply

**Comment by Berkayreb** [comment]
it is solved

**Comment by owairc** [comment]
how did you solve? I hit the same issue

**Comment by Berkayreb** [comment]
I cover the card with div as image
![image](https://user-images.githubusercontent.com/45543505/221272275-15be6369-6795-420a-8aa3-c12e99894e67.png)

After i added to css this tags

.custom-node .port {
    width: 20px;
    height: 20px;
    border-radius: 50%;
    background-color: #79bcdb;
    border: 3px solid #29A9E5;
    cursor: pointer;
    visibility: visible;
}

.custom-node .port.bottom {
    position: absolute;
    bottom: -10px;
    left: 33px;
}


.custom-node .port.right {
    position: absolute;
    bottom: 33px;
    left: 73px;
}

.custom-node .port.left {
    position: absolute;
    bottom: 33px;
    left: -11px;
}


.custom-node .port.top {
    position: absolute;
    bottom: 73px;
    left: 33px;
}


.custom-node .port:hover, .custom-node .port.has-links, .default.group .port.has-links {
    background-color: black;
}

**Comment by owairc** [comment]
thanks!
