### ISSUE TITLE
Node sticks to cursor bug.

### ISSUE THREAD

**Issue by TZBlockBuster** [Blazor-Diagrams/Blazor.Diagrams#310]
When you have a `<Select>` Dropdown Menu inside a node and you open the dropdown and select something. Then the node is stuck to your Cursor and you have to reload the page in order to continue. While you are dragging there must be a check if you are still holding the mouse key. I guess... Would be awesome if this can be fixed.

**Comment by zHaytam** [comment]
Do you mean that if you select an item from the dropdown and you start moving your mouse, it will move the node? As if you clicked the node?

**Comment by zHaytam** [comment]
What version are you using?

**Comment by zHaytam** [comment]
Can you show me the code of your node?

**Comment by zHaytam** [comment]
Can you try:
<div class="card VariableNode @(Node.Selected ? " selected" : "")">
    <div style="display: flex; flex-direction: row; align-items: center; margin-right: -11px;">
        <div class="card-body">
            <h5 class="card-title">Variable</h5>
            <div class="form-group" @onmousedown:stopPropagation @onmousemove:stopPropagation>
                <input type="text" class="form-control" placeholder="Variable Ident" @bind="Node.VarName"/>
                <select class="form-select" style="margin-top: 5px; margin-bottom: 5px;" @bind="Node.VarType">
                    <option value="@VariableType.Static">Static</option>
                    <option value="@VariableType.Dynamic">Dynamic</option>
                </select>
                @if (Node.VarType == VariableType.Static)
                {
                    <input type="text" class="form-control" placeholder="Value" @bind="Node.VarValue"/>
                }
            </div>
        </div>
        <TextPortComponent Node="Node" Alignment="PortAlignment.Right"></TextPortComponent>
    </div>
</div>

**Comment by TZBlockBuster** [comment]
Oh thank you, it's working now!

**Comment by zHaytam** [comment]
Great, I will close this issue then!
