### ISSUE TITLE
Can I set parameters to fix a certain node?

### ISSUE THREAD

**Issue by whugarra** [Blazor-Diagrams/Blazor.Diagrams#311]
I need to set a node that cannot be moved or deleted. Can this be implemented?

**Comment by 314159265meow** [comment]
Hello, have you tried the `Locked` property of a node? See this demo here https://blazor-diagrams.zhaytam.com/demos/locked

**Comment by zHaytam** [comment]
Hey, as @314159265meow said, check out the `Locked` property, as well as the `ShouldDeleteNode` option in constraints.

**Comment by whugarra** [comment]
Wow，It's so cool to have this demonstration. Thank you very much.
