### ISSUE TITLE
Resize nodes

### ISSUE THREAD

**Issue by Heathermcx** [Blazor-Diagrams/Blazor.Diagrams#324]
Hi, we would like to be able to resize nodes by adding resizers to a node (similarly to how ports are added). When a resizer is dragged, the node changes size accordingly. We have created[ this PR](https://github.com/Blazor-Diagrams/Blazor.Diagrams/pull/319) to implement it. Please take a look and let us know if you have any concerns or questions.

**Comment by zHaytam** [comment]
I have replied to your PR directly
