### ISSUE TITLE
Diagram.RegisterComponent no longer exists in 3.0. What is the replacement?

### ISSUE THREAD

**Issue by LuckyScamper** [Blazor-Diagrams/Blazor.Diagrams#330]
To register a view with a component, say a group or node, one could perform _diagram.RegisterComponent<Foo, FooView>_. However, in the beta this method has been removed, and I can't see its replacement (or new way of implementation, say a factory) nor in the examples since those examples haven't been in updated yet.

**Comment by zHaytam** [comment]
Hello,

Since the new version, `Diagram` (available in the Core package) doesn't reference Blazor, so those methods have moved to the new implementation of diagram, `BlazorDiagram`.

See https://github.com/Blazor-Diagrams/Blazor.Diagrams/blob/develop/src/Blazor.Diagrams/BlazorDiagram.cs#L30

**Comment by LuckyScamper** [comment]
Thanks, issue fixed
