### ISSUE TITLE
Is it possible to implement a Gantt chart using your library?

### ISSUE THREAD

**Issue by Amir0715** [Blazor-Diagrams/Blazor.Diagrams#332]
Hi, I want to implement a Gantt chart and after studying the documentation, I'm almost sure I can do it using your abstractions.
Approximately what I want to get:
https://frappe.io/gantt

Do you think it is possible to do this?

**Comment by zHaytam** [comment]
Hey!

Is it possible? Yes.
Would I recommend it? No.

This library will be too overkill for something that can be done without. A Gantt chart is really made up of nodes/ports, the links are only 1 variant, etc...

But if you want to still do it, I can answer any questions you might have!

**Comment by Amir0715** [comment]
What difficulties do you think might arise?

**Comment by zHaytam** [comment]
I wouldn't say there will be difficulties if you use the library, I'm just saying that you will not be using a lot of features.
