### ISSUE TITLE
DOM is not updating after mouse click event

### ISSUE THREAD

**Issue by Kbarude** [Blazor-Diagrams/Blazor.Diagrams#333]
Blazor Web assembly --> package : z.Blazor.Diagram 

<CascadingValue Value="diagram" >
        <DiagramCanvas></DiagramCanvas>
    </CascadingValue>
@if(ShowComponent){
//Load table
}

@code{
public bool ShowComponent { get; set; }
diagram.MouseClick += MouseClickEvent;
 private void MouseClickEvent(Model sender,MouseEventArgs e)
    {
ShowComponent=true;
}
}

mouse click event is working and showcomponent property is setting to true, but this property change is not render on DOM, any variables inside the mouseclick is not render on DOM.
What is the wrong in this code, please let me know

----

**Comment by zHaytam** [comment]
Hi, try adding `InvokeAsync(StateHasChanged);` after `ShowComponent=true;`.
