### ISSUE TITLE
How to get both attached node models from a link information.

### ISSUE THREAD

**Issue by ATEEKGIT** [Blazor-Diagrams/Blazor.Diagrams#342]
My nodes are custom model is holding data inside , when nodes are linked i need to some how know programmatically which node attached to which node , i tried Diagram.Nodes.First().Links and then lost where is next node information is stored.

any idea to identify programmatically , the both nodes models attached to a link as source and target 

currently I am trying version 3 and its just excellent , please accept a heartly thanks from my side.

**Comment by zHaytam** [comment]
If you are connecting links between 2 nodes directly:
```cs
var sourceNode = (link.SourceAnchor as ShapeIntersectionAnchor)!.Node;
// OR
var sourceNode = link.SourceAnchor.Model as NodeModel; // or your custom type
```

If you're using ports:
```cs
var sourceNode = (link.SourceAnchor as SinglePortAnchor)!.Port.Parent;
// OR
var sourceNode = (link.SourceAnchor.Model as PortModel)!.Parent; // or your custom type
```

**Comment by ATEEKGIT** [comment]
thanks , this worked for me , TaskPort is my custom port.

var targetNode = (link.Target.Model as TaskPort).Parent;
