### ISSUE TITLE
How can we capture the Event for Add connection and Remove Connetion on a Port , or in any case

### ISSUE THREAD

**Issue by ATEEKGIT** [Blazor-Diagrams/Blazor.Diagrams#344]
Trying to figure out how to get Add connection and Remove connection event on a port , as when user drag a link and connect to a port that time needs to execute my code.

its version 3.0 

Even if there is any place where we can capture this link/unlink event either global level that will be fine.

Appreciate your support.

**Comment by ATEEKGIT** [comment]
it is version 3.0

**Comment by zHaytam** [comment]
You have the general `Diagram.Links.Added` event, which should be your first step.  
This event is triggered when a link is added, either manually or when the user starts dragging from a port.  

To check if the link is new and its from a port, simply do `newLink.Source is SinglePortAnchor && !newLink.Attached`.

If you want to know when that link got attached, you have to use the link events `Attached` and `TargetChanged`

**Comment by ATEEKGIT** [comment]
it worked perfectly the way i needed , sorry for disturbance , in absense of documentation i could not figure it out myself ,  you are love  :) thanks aloooooot
