### ISSUE TITLE
How can reset lines...

### ISSUE THREAD

**Issue by avap90** [Blazor-Diagrams/Blazor.Diagrams#352]
Hi. Thank you for your Blazor-Diagrams..

Some many rects and connect lines..

but connected lines are complicated.

How can reset line this style..

![image](https://github.com/Blazor-Diagrams/Blazor.Diagrams/assets/16488571/06d04383-feaf-4985-b7ec-55cadc7e9543)

Is possble?

Thank you for your project.

**Comment by zHaytam** [comment]
I'm sorry I don't understand what you want to achieve...
Do you want lines to go like this?

![image](https://github.com/Blazor-Diagrams/Blazor.Diagrams/assets/34218324/9522c609-a65b-405a-a0a7-837e2bcb3391)

**Comment by avap90** [comment]
> I'm sorry I don't understand what you want to achieve... Do you want lines to go like this?
> 
> ![image](https://user-images.githubusercontent.com/34218324/265812829-9522c609-a65b-405a-a0a7-837e2bcb3391.png)

Oh.. Hi!~ Thank you for your answer.

My meen is this.
![image](https://github.com/Blazor-Diagrams/Blazor.Diagrams/assets/16488571/5cd98de7-e9aa-45a4-bb9c-9ec5f1cf8dcd)

If i create auto reset button. 
button click auto reset clean position.

Thank you  for your answer.

**Comment by zHaytam** [comment]
You will need to use a Layout Algorithm.  
Unfortunately, the library doesn't provide them for now.
