### ISSUE TITLE
Link Labels don't render on Firefox

### ISSUE THREAD

**Issue by Mr-Technician** [Blazor-Diagrams/Blazor.Diagrams#377]
Link labels do not render at all when using Firefox. This can be reproduced on the [Blazor Diagrams home page](https://blazor-diagrams.zhaytam.com/):
![image](https://github.com/Blazor-Diagrams/Blazor.Diagrams/assets/26885142/399afb18-2d90-490c-b56e-4271db72c74a)

Expected result:
![image](https://github.com/Blazor-Diagrams/Blazor.Diagrams/assets/26885142/68243581-c369-4761-bb82-69c9e5857e0d)

I have tested Firefox on (latest version except in the last case):

- My work dev VM, Windows 10
- A baremetal Windows 10 desktop
- A hyper-V Windows 11 VM
- Citrix VDI

All cases had the same issue.

**Comment by prof3000** [comment]
Good day, please how to make label link not blue background color, how to make nodemodel make background red or green. Best regards

**Comment by zHaytam** [comment]
Hello, I'll check this and get back to you!

**Comment by prof3000** [comment]
Ok , good day, I need sample how to change color background of nodes box.

**Comment by Mr-Technician** [comment]
@prof3000 please make a new issue, this issue is for the problem described at the top.

**Comment by prof3000** [comment]
Mr-Technician not issue, I need how to make 
Background color red or green of nodemodel.

**Comment by Sycha** [comment]
I have had the same problem. I found that firefox doesn't display foreignObject elements that don't have a height and width defined. I was able to create a work around by adding to the css of a parent element:

::deep foreignObject.diagram-link-label {
    width: 1px;
    height: 1px;
}

It still works on Edge and Chrome.

I hope that helps

**Comment by zHaytam** [comment]
1px seems to be enough since in CSS I already added `overflow: visible;`, I will add this to the next version!
