### ISSUE TITLE
Is there anyway to add more action when the node/link is deleted (by pressing 'del' button)?

### ISSUE THREAD

**Issue by JanOfOlympus** [Blazor-Diagrams/Blazor.Diagrams#384]
I want to add some more action when node/link is deleted and or change

I notice that when I press 'del' button on the selected node, the node is deleted from the canvas.  But I don't know where does this action triggered and can we know that it's been triggered so I can add some more action there. :)

Thank so much :)

**Comment by zHaytam** [comment]
Hello, please check the `Diagram.Nodes.Removed` and `Diagram.Links.Removed` events.

**Comment by zHaytam** [comment]
You also have `Constraints` in the options where you can decide whether to delete something or not.  
For now I will close this, feel free to re-open if you have any more questions!
