### ISSUE TITLE
Support for .Net 8

### ISSUE THREAD

**Issue by Trubador** [Blazor-Diagrams/Blazor.Diagrams#412]
I am getting this issue trying to get the package working on .Net 8 for the following diagram component page: "The name Diagrams does not exist in this context".

@using Blazor.Diagrams.Components

<div class="diagram-container">
    <CascadingValue Value="Diagram" IsFixed="true">
        <DiagramCanvas></DiagramCanvas>
    </CascadingValue>
</div>

This is using the latest installation and setup documentation from: https://blazor-diagrams.zhaytam.com/

Do you have any hints about what might be the issue?

**Comment by TheCyberCore** [comment]
Not much input in your question... It is hard to guess your problem. For me, version 3.0.1 works like a charm in .NET 8.0.
Here some extracts from the code I am using in .NET 8.0

`private BlazorDiagram _diagram { get; set; }
protected override void OnInitialized()
{
    base.OnInitialized();

    var options = new BlazorDiagramOptions
    {
        Zoom = { Enabled = true, ScaleFactor = 1.5 },
        AllowMultiSelection = false, // Whether to allow multi selection using CTRL
        Links =
        {
            DefaultRouter = new NormalRouter(),
            DefaultPathGenerator = new SmoothPathGenerator()
        }
    };

    _diagram = new BlazorDiagram(options);

    // .... Your diagram drawing code goes here
}
`

Razor part
`
<CascadingValue Value="_diagram" IsFixed="true">
      <div style="width:1800px;height:800px;">
         <DiagramCanvas></DiagramCanvas>
       </div>
</CascadingValue>
`

**Comment by Trubador** [comment]
@TheCyberCore Thanks for the example code. I will try it out. So far I moved the Diagram code to a Net 7 project and it works just fine there so I figured it would be Net 8 that was the cause of failure and thus did not include my code initially in this ticket.
