### ISSUE TITLE
NullReferenceException in `DiagramCanvas.OnInitialized()` on .NET 8

### ISSUE THREAD

**Issue by Joe4evr** [Blazor-Diagrams/Blazor.Diagrams#424]
Found while upgrading a company codebase to .NET 8, rendering a `DiagramCanvas` always triggers NRE.
```
Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Blazor.Diagrams.Components.DiagramCanvas.OnInitialized()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

[Looking at the implementation of `DiagramCanvas.OnInitialized`](https://github.com/Blazor-Diagrams/Blazor.Diagrams/blob/ac4eef3d8e4ef0cc5a7caabfda33864d154890be/src/Blazor.Diagrams/Components/DiagramCanvas.razor.cs#L49-L55), the only thing would reasonably be causing the NRE is `BlazorDiagram.Changed += OnDiagramChanged;`. I can confirm the diagram that we pass in is *non*-null, but it's also pretty sus that that line isn't in `OnParametersSet` instead.

In fact, I'm amazed that all of this worked *at all* previously, since the `DiagramCanvas` hasn't been touched for 2 years, and [Blazor's initialation logic](https://github.com/dotnet/aspnetcore/blob/449abac6f1ca12fa0ad557a872c219fcdfae09f3/src/Components/Components/src/ComponentBase.cs#L247) hasn't been touched in *3* years (meaning it has always called `OnInitialized()` before `OnParametersSet()`).

This is blocking our upgrade to .NET 8, and that in turn is blocking other work items.

**Comment by Joe4evr** [comment]
*Sigh* Nevermind, seems like I didn't catch having to change our diagram field being typed as `Diagram` to `BlazorDiagram`. 🤦

**Comment by zHaytam** [comment]
That's what I was gonna say, but got caught up at work sorry!
