### ISSUE TITLE
PortAligment

### ISSUE THREAD

**Issue by kg9316** [Blazor-Diagrams/Blazor.Diagrams#462]
How to add multiple ports ? (like the databaseDesigner Example) in ver 3 ?

**Comment by zHaytam** [comment]
Hello,

You can use as many `node.AddPort` as you want, I'm afraid I don't understand why you wouldn't be able to.

Do you have a specific scenario that doesn't work, or maybe a piece of code?

For now I'll close this, but please don't hesitate to open it again with more information/questions!
