### ISSUE TITLE
How do I fix the diagram?

### ISSUE THREAD

**Issue by wubing7755** [Blazor-Diagrams/Blazor.Diagrams#464]
Implement the canvas in a fixed window position, the size is 1200x600, and the mouse is not allowed to drag the diagram.

**Comment by wubing7755** [comment]
Problem description: When I stretch Node with JS implementation, the canvas moves with the mouse.

**Comment by jokerclay** [comment]
> Problem description: When I stretch Node with JS implementation, the canvas moves with the mouse.

if you trying to  stretch the Node, that means you may have control points anround the node, here is what I thinking

* when the mouse on the control point and mousedown , `node.lockd = true` that lock the node
* when mousmoving, do the computation
* when mouseup unlock the node by  `node.lockd = false`

**Comment by wubing7755** [comment]
> > Problem description: When I stretch Node with JS implementation, the canvas moves with the mouse.
> 
> if you trying to stretch the Node, that means you may have control points anround the node, here is what I thinking
> 
> * when the mouse on the control point and mousedown , `node.lockd = true` that lock the node
> * when mousmoving, do the computation
> * when mouseup unlock the node by  `node.lockd = false`

Thank you so much for your suggestion, jokerclay. My colleague and I have implemented the stretch node function following your advice. Wishing you a wonderful day!

**Comment by zHaytam** [comment]
Do you maybe want to disable panning? `yourDiagram.Options.AllowPanning = false;`
