### ISSUE TITLE
Get position value from diagram

### ISSUE THREAD

**Issue by JEDII29** [Blazor-Diagrams/Blazor.Diagrams#465]
I use DiagramCanvas to display nodes, and I want to continuously update the positions of the Nodes in another collection. Is it possible to listen for position changes so that I can trigger a method to update the data? Alternatively, can I add a handler to the Diagram.Nodes objects for the onMouseClick event?

**Comment by zHaytam** [comment]
Hello, all movable models (e.g. nodes) have a `Moved` event, did you try using that?

For all mouse events, check out the pointer events in the diagram.

**Comment by zHaytam** [comment]
I hope that that's what you were looking for, don't hesitate to re-open this issue if it's not!
