### ISSUE TITLE
Turn off automatic compression in Excubo.WebCompiler

### ISSUE THREAD

**Issue by robertmclaws** [Blazor-Diagrams/Blazor.Diagrams#471]
By default, Exubo.WebCompiler outputs gzipped resources. Normally that is awesome, but in Blazor's case it is [causing issues with .NET 9.0](https://github.com/dotnet/aspnetcore/issues/57512).

[According to this](https://github.com/excubo-ag/WebCompiler?tab=readme-ov-file#breaking-changes-in-version-20x), you'll need to add the `--zip disable` flag to the target to let .NET do its thing instead.

I will also open a ticket in Exubo.WebCompiler to detect if it's running in a Razor SDK and disable automatic compression.

**Comment by zHaytam** [comment]
You are great, thank you!

I will incorporate this as soon as I can.

**Comment by robertmclaws** [comment]
If you could also please add .NET 9 targets directly, so it builds for .NET 8.0 and 9.0, that would be awesome.

If you need help, here is an example of how to do platform-specific package references, with the proper ranges. Make sure you allow for proper ranges and wildcards so that .NET 8 people can use DI 9.0 packages if they need to, etc.

Thanks so much!

**Comment by zHaytam** [comment]
3.0.3 is out in NuGet, and it includes a fix for this, check it out!

I'll close this for now, but feel free to re-open if something is wrong.
