### ISSUE TITLE
Bug when setting node.Visible false on node creation

### ISSUE THREAD

**Issue by alamfaust** [Blazor-Diagrams/Blazor.Diagrams#476]
When setting node.Visible=false on node creation, exception: 
`Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'. ` is thrown.
[https://github.com/Blazor-Diagrams/Blazor.Diagrams/blob/62ca0e55c36d851f7663b61a5fa671bfbc09302b/src/Blazor.Diagrams/Components/Renderers/NodeRenderer.cs#L136
](url) maybe Visible needs to get checked before registering the observer.

**Comment by zHaytam** [comment]
3.0.3 is out in NuGet, and it includes a fix for this, check it out!

I'll close this for now, but feel free to re-open if something is wrong.
