### ISSUE TITLE
Any way to set per-axis padding?

### ISSUE THREAD

**Issue by JayVDZ** [Blazor-Diagrams/Blazor.Diagrams#479]
I've created a custom group which needs more top padding that side and bottom, but don't see a way to achieve this. At the moment I can either pad the hell out of it and have super big groups, or tight padding and then the children push up into the top of the group. Ideally I want to say:

padding-top: 60
padding-left: 30
padding-right: 30
padding-bottom: 30

i.e. with enough, but too much padding:

<img width="175" alt="image" src="https://github.com/user-attachments/assets/a7233dd4-2136-4293-b6f8-364e7bec5446">

Is there a way to achieve this?

**Comment by JayVDZ** [comment]
Move on from this due to no answer.

**Comment by zHaytam** [comment]
Hello, so sorry for not replying sooner.

Unfortunately, the padding is 1 number right now, so it's the same for all sides. It shouldn't be hard to modify, I would be happy to look for a PR, otherwise, it'll have to wait a bit until I can do it!
