### ISSUE TITLE
Build error when targeting .net 9.0

### ISSUE THREAD

**Issue by stavroskasidis** [Blazor-Diagrams/Blazor.Diagrams#480]
Hello,

The following error occurs when the project is build using .net 9.0. My guess is that there is a conflict with the new static assets feature of .Net 9.0

`C:\Program Files\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets(614,5): error : Conflicting assets with the same target path '_content/Z.Blazor.Diagrams/default.styles.min.css.gz'`

**Comment by zHaytam** [comment]
This is probably related to #471 right?

**Comment by stavroskasidis** [comment]
Yes it seems so. I will close this in favor of #471

**Comment by robertmclaws** [comment]
@stavroskasidis in the meantime, just add this to your project:

```xml
	<Target Name="RemoveConflictingAssets" BeforeTargets="ResolveStaticWebAssetsConfiguration">
		<ItemGroup>
			<StaticWebAsset Remove="@(StaticWebAsset)" Condition="'%(Extension)' == '.gz'" />
		</ItemGroup>
	</Target>
```
