### ISSUE TITLE
.NET 9 support

### ISSUE THREAD

**Issue by jimitndiaye** [Blazor-Diagrams/Blazor.Diagrams#483]
>  warning NU1608: Detected package version outside of dependency constraint: Z.Blazor.Diagrams 3.0.2 requires Microsoft.AspNetCore.Components.Web (>= 8.0.0 && < 9.0.0) but version Microsoft.AspNetCore.Components.Web 9.0.0 was resolved.

The Blazor Diagrams package explicitly excludes .NET 9 (even though there shouldn't be any direct blockers to the upgrade - no breaking changes that should affect blazor diagrams as far as I can see). 

We are attempting to upgrade to .NET 9 but this dependency is currently a blocker. Please help.

**Comment by rborosak** [comment]
+1

**Comment by RicoSuter** [comment]
Same problem here... why is .NET 9 excluded?

**Comment by alphamax** [comment]
interested here :)

**Comment by rogerjak** [comment]
It's been over a week and no comment from any maintainer.
Should we have to migrate to the "competitor" Excubo just for this?

**Comment by thatstatsguy** [comment]
@zHaytam is there someone else who can review the PR if you're busy with other work?

**Comment by TheBigNeo** [comment]
I have written an e-mail to zHaytam. I hope he has time for it. 😄

**Comment by zHaytam** [comment]
Hello, I have merged the PR, the NuGet package should be up to date around lunch, I'll finish up some meetings, include 1 or 2 more changes and upload it.

Sorry!

**Comment by GordonBeeming** [comment]
Thanks @zHaytam 💪 ... and I'm assuming @TheBigNeo for the email that likely lead to @zHaytam checking out this issue 😅

**Comment by alphamax** [comment]
Thanks

**Comment by zHaytam** [comment]
Is it me or there is no way to tell Github Actions to use .NET 9?

**Comment by zHaytam** [comment]
3.0.3 is out in NuGet, check it out!

I'll close this for now, but feel free to re-open if something is wrong.
