### ISSUE TITLE
Questions from MichaelLant

### ISSUE THREAD

**Issue by zHaytam** [Blazor-Diagrams/Blazor.Diagrams#80]
I also have a requirement that in certain circumstances only one node is allowed.

I also need to be able to place nodes programatically in specific locations on objects. 

As well, I need to have a directionality to nodes where a node can be either an Input Port or an Output Port. Input Ports can connect only to Output Ports. Input Ports cannot connect to Input Ports and Output Ports cannot connect to Output Ports. This is not something that I think that I see Blazor.Diagrams doing directly as there are domain rules associated with how, when and how many ports can be added or removed as well as where the Ports are located. To be more specific, I need to be able to enforce Input Port locations only on the left side of an object and Output Ports on the right side. The reason for controlling the location of the Ports by type is to create a visual workflow for processes (manufacturing, scheduling, chemical reactions, etc.).

I have not yet dug deep enough into the existing capabilities It would be terrific to have that level of control over Nodes/Ports.

I have two projects in mind where I already know all of the connection and containership rules that I need to enforce. If it would help, I can write something that describes the rules in a generic form that describes the functionality without describng the the projects. Please let me know if that would help.

Michael

_Originally posted by @MichaelLant in https://github.com/zHaytam/Blazor.Diagrams/issues/79#issuecomment-776348052_

**Comment by zHaytam** [comment]
> Input Port or an Output Port. Input Ports can connect only to Output Ports.

This is possible by creating a custom Port class. There, you can override `CanAttachTo` and decide whether a link between two ports and attach or not. You would have a boolean in your port class that tells you whether it's input or ouput.

> I need to be able to enforce Input Port locations only on the left side of an object and Output Ports on the right side.

Just set the correct port alignments (so that links are drawn correctly) and use CSS to position the ports wherever you wish.

If you have any other question, let me know!

**Comment by MichaelLant** [comment]
Thanks @zHaytam 

You've done some great work here!

**Comment by zHaytam** [comment]
Closing this as it's not really an issue.
Feel free to re-open if you have any other questions, especially after 2.0.0!
