### ISSUE TITLE
Using Diagram before it is fully loaded

### ISSUE THREAD

**Issue by BjornEngelen** [Blazor-Diagrams/Blazor.Diagrams#86]
Hi, great work on 2.0.0!

When I try to add nodes to the diagram programatically in the OnInitializedAsync method of the page

```
var position = Diagram.GetRelativePoint(x, y);
var node = new FunctionNodeModel(function, position);
Diagram.Nodes.Add(node);
```

 this happens:

```
System.Exception: Container not available. Make sure you're not using this method before the diagram is fully loaded
   at Blazor.Diagrams.Core.Diagram.GetRelativePoint(Double clientX, Double clientY)

```

This did not happen in the previous release. Is there a workaround such as an event I should be waiting for?

Thanks

**Comment by zHaytam** [comment]
Hello and thanks!
The problem here is with `GetRelativePoint`, which calculates the relative point based on the canvas container. While the canvas didn't render, `Container` is null, so the calculation isn't possible.
The previous version returned `null` in that case, but I felt that it doesn't make a lot of sense since you shouldn't be using methods that depend on `Container` before it's initialized.

Solution: Don't use those methods in `OnInitializedAsync`. Just set the position to null or something you already know.
Hope this helps!

**Comment by BjornEngelen** [comment]
I have the same result using OnAfterRenderAsync instead of OnInitializedAsync. How can I be alerted when the container is initialized?

**Comment by zHaytam** [comment]
There is a `ContainerChanged` event in `Diagram`. May I know why you need the relative point?

**Comment by BjornEngelen** [comment]
Upon investigation it seemed that we could eleminate the relative point. It was being called from a function that handled adding custom nodes and custom ports both at initialization and when when using drag/drop mouse interaction. It was not needed when seeding the diagram.

However I'm still encoutering a problem without it:

crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Blazor.Diagrams.Components.DiagramCanvas.get_LayerStyle()
   at Blazor.Diagrams.Components.DiagramCanvas.BuildRenderTree(RenderTreeBuilder __builder)

I'll build a minimal example and see if I can isolate the problem

**Comment by BjornEngelen** [comment]
Hello, you can find a minimal example here using blazor webassembly:

https://github.com/BjornEngelen/DiagramIssue

Upon opening the page, an error occurs

**Comment by zHaytam** [comment]
Hello, not sure if it's normal but you're not setting a value to `Diagram`.

Anyway, in 2.0.0, there is no need to specify `Name` in the cascading value. Please use this: `<CascadingValue Value="Diagram">`. 
Tell me if you have any other issues.
