### ISSUE TITLE
Save/Open diagram

### ISSUE THREAD

**Issue by VladislavAntonyuk** [Blazor-Diagrams/Blazor.Diagrams#89]
Add method to allow serializing/deserializing diagram

**Comment by zHaytam** [comment]
Hello,
I have thought about this for a LONG time before releasing version 2. The problem here is that every use case is different, every person will want to export to some provider in some way and I didn't find a good enough solution to help everyone.

A good enough solution, for most use cases, would be to just handle JSON only and let the user handle other providers himself. What do you think?

I'm happy to discuss this to find the best solution possible.

**Comment by VladislavAntonyuk** [comment]
I think starting from the Json would be the best. Later the community can add other serializations (like Binary and XML serialization)

**Comment by michalss** [comment]
PLease implement this save/open is basically need to have :)

**Comment by zHaytam** [comment]
I am really trying but System.Text.Json doesn't even handle subtypes, so custom models won't be correctly (de)serialized.

**Comment by michalss** [comment]
Just just Newjson instead.. :) it is much better..

**Comment by zHaytam** [comment]
May I know how do you expect to use this feature? A sample of code would great, just to see how you want it to look like.

**Comment by VladislavAntonyuk** [comment]
var data = Diagram.Save(Format.Json);

Diagram.Load(data, Format.Json);

**Comment by xhydongda** [comment]
@zHaytam Try [this](https://stackoverflow.com/questions/65193093/can-newtonsoft-properly-deserialize-a-list-of-inherited-or-subclass-objects) to (de)serialize subtypes properly.

**Comment by xhydongda** [comment]
@zHaytam I successfully saved a Diagram(A) to json file, and recreate a Diagram(B)  using presaved json file. 
My question: how to replace Diagram A with B and rerender the component?

**Comment by zHaytam** [comment]
I am not sure if I understand it correctly, usually if you load the presaved diagram it will be in OnInitialized so that would be your instance no? If you're loading it later, wouldn't replacing the Diagram instance cause it to rerender?

**Comment by xhydongda** [comment]
By simply replace A with B，I got Container is null exception.
Then, I saved A's Container to json and retry, I got nothing in html(both svg and div layers are empty).
I also called OnAfterRenderAsync(true), still nothing.

**Comment by zHaytam** [comment]
Would it be possible for you to make a small repo that shows the issue? It would help a lot.

**Comment by xhydongda** [comment]
Just have a try in Simple demo:

1. change ToggleZoom in Simple.razor.cs  to:
protected void ToggleZoom()
{
    var diagramB = new Diagram();
    var node1 = NewNode(50, 50);
    diagramB.Nodes.Add(new[] { node1 });
    diagram = diagramB;
}

2. make diagram not readonly.

**Comment by xhydongda** [comment]
I fork and push serializable changes in the [code](https://github.com/xhydongda/Blazor.Diagrams/tree/master/src/Blazor.Diagrams.Core).
As add [JsonIgnore] directly to model bringing in chaos，and delegate can't be serialized，
I introduce twin models with only properties need to be serialized，and replace reference object with Id.
May not good enough, just a choice.

**Comment by zHaytam** [comment]
Part of #218
