### ISSUE TITLE
Cannot Compile: private NodeModel NewNode(double x, double y) 

### ISSUE THREAD

**Issue by MichaelLant** [Blazor-Diagrams/Blazor.Diagrams#93]
I am stuck on the updates from the earlier versions.

From the Getting Started example:

`    private NodeModel NewNode(double x, double y)`

This line does not compile. I get the following error:

`Error	CS0246	The type or namespace name 'Point' could not be found (are you missing a using directive or an assembly reference?)`

What am I doing wrong?

**Comment by zHaytam** [comment]
Hello,
You're just missing a using statement, VS should helo you with that normally.

Its `using Blazor.Diagrams.Core.Geometry`.

**Comment by MichaelLant** [comment]
Thanks! That fixed the problem.

It would be useful to include that in the Getting Started guide, especially given the fact that Intellisense doesn't actually work in VS 2019 Preview.

**Comment by zHaytam** [comment]
I will do that as soon as I can, thank you.
