### ISSUE TITLE
Deleting link on portless node leaves dangling link - inconsistent with ported node

### ISSUE THREAD

**Issue by TrevorDArcyEvans** [Blazor-Diagrams/Blazor.Diagrams#96]
Steps to reproduce:
1. https://blazor-diagrams.zhaytam.com/nodes/portless-links
2. select blue node
3. press delete key
4. blue node is deleted

Observed:
* link is not deleted
* end of link is free where it was connected to blue node

Expected:
* link should be deleted
* behaviour should be consistent with nodes with ports eg:
  * https://blazor-diagrams.zhaytam.com/nodes/svg

**Comment by zHaytam** [comment]
Indeed, thank you for reporting that.
I'll fix it as soon as I can.
