### ISSUE TITLE
Cannot click elements inside foreignObject in link labels

### ISSUE THREAD

**Issue by mertoral** [Blazor-Diagrams/Blazor.Diagrams#97]
Cannot click elements inside foreignObject in link labels

```
<foreignObject class="label-wrapper" x="@((X-2).ToInvariantString())" y="@Y.ToInvariantString()" style="overflow:visible" pointer-events="all">
    <div xmlns="http://www.w3.org/1999/xhtml" class="link-label" style="border-radius: 50%; background-color: white; border: 1px solid black; cursor: pointer;>
        **<a onclick="javascript:alert('hi');">**
            <i class="fa fa-plug" style="color:black"></i>
        </a>
    </div>
</foreignObject>
```

**Comment by zHaytam** [comment]
Hello, this is a limitation of Blazor, not the library.
https://github.com/dotnet/aspnetcore/issues/18271

**Comment by mertoral** [comment]
You caught me.. I thought I could sneak it in.

Here is a work around I ended up with in case anyone is as desperate as I am for this.

Clicks on <g class="line" work ok

Create a custom label, id the foreignobject, 
back it with some js, 
invoke js  
     init passing custom label as dotNetObject, 
     traverse up from foreignobject, 
     attach a click handler to g class="link", 
     
     handle click and invoke onclick on blazor side. 

Ps: avoid dupe handlers on js side using link id.

**Comment by zHaytam** [comment]
That's how I do it too.
I'll close this since it's not an issue, thanks!
