### ISSUE TITLE
Components missing from Blazor.Diagrams.Core

### ISSUE THREAD

**Issue by ZeroRadius** [Blazor-Diagrams/Blazor.Diagrams#98]
Hello, I seem to be missing something. I am following the getting started page, it has me do @using Blazor.Diagrams.Components;  but this causes an error which is causing <DiagramCanvas></DiagramCanvas> to have an error. Here are the two errors Severity	

Error	CS0234	The type or namespace name 'Components' does not exist in the namespace 'Blazor.Diagrams' (are you missing an assembly reference?)	

AND

Error		Found markup element with unexpected name 'DiagramCanvas'. If this is intended to be a component, add a @using directive for its namespace.	

Sorry if this is the wrong place, I did not know where else to post for help with this.

**Comment by zHaytam** [comment]
Hello,
I just created a new project and added:
```
@using Blazor.Diagrams.Core;
@using Blazor.Diagrams.Core.Models;
@using Blazor.Diagrams.Components;
```

Then:
```
<!-- Add this where you want to show the diagram -->
<CascadingValue Value="Diagram">
    <DiagramCanvas></DiagramCanvas>
</CascadingValue>
```

And it's working as expected.  
Are you sure you installed the package? Maybe you installed `Blazor.Diagram.Core` instead of `Blazor.Diagram`?

**Comment by ZeroRadius** [comment]
Ah, sorry this is my first time using NuGet Packages, I did indeed download Blazor.Diagram.Core
